/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthPathnameRouteImport } from './routes/auth/$pathname'
import { Route as ArenaArenaIdRouteImport } from './routes/arena/$arenaId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthPathnameRoute = AuthPathnameRouteImport.update({
  id: '/auth/$pathname',
  path: '/auth/$pathname',
  getParentRoute: () => rootRouteImport,
} as any)
const ArenaArenaIdRoute = ArenaArenaIdRouteImport.update({
  id: '/arena/$arenaId',
  path: '/arena/$arenaId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/arena/$arenaId': typeof ArenaArenaIdRoute
  '/auth/$pathname': typeof AuthPathnameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/arena/$arenaId': typeof ArenaArenaIdRoute
  '/auth/$pathname': typeof AuthPathnameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/arena/$arenaId': typeof ArenaArenaIdRoute
  '/auth/$pathname': typeof AuthPathnameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/arena/$arenaId' | '/auth/$pathname'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/arena/$arenaId' | '/auth/$pathname'
  id: '__root__' | '/' | '/arena/$arenaId' | '/auth/$pathname'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArenaArenaIdRoute: typeof ArenaArenaIdRoute
  AuthPathnameRoute: typeof AuthPathnameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/$pathname': {
      id: '/auth/$pathname'
      path: '/auth/$pathname'
      fullPath: '/auth/$pathname'
      preLoaderRoute: typeof AuthPathnameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arena/$arenaId': {
      id: '/arena/$arenaId'
      path: '/arena/$arenaId'
      fullPath: '/arena/$arenaId'
      preLoaderRoute: typeof ArenaArenaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArenaArenaIdRoute: ArenaArenaIdRoute,
  AuthPathnameRoute: AuthPathnameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
